import {test,expect} from '@playwright/test';
import path from 'node:path';
const web=process.env.TEST_WEB_URL||'http://127.0.0.1:3001';
const api=process.env.TEST_API_URL||'http://127.0.0.1:8000';
// A generated test label. Entered registry details are simulated, never live GS1 evidence.
test('barcode identity compares, persists, exports and recovers without altering the audit',async({page,request})=>{
  test.setTimeout(180000);
  const errors:string[]=[];const gs1Requests:string[]=[];
  page.on('pageerror',e=>errors.push(e.message));
  page.on('request',r=>{if(new URL(r.url()).hostname.endsWith('gs1.org'))gs1Requests.push(r.url());});
  await page.addInitScript(()=>localStorage.setItem('doca_tour_done','true'));
  await page.goto(web);
  await page.locator('#tabOfficerBtn').click();await page.locator('#officerIdInput').fill('barcode-fixture-reviewer');await page.locator('#officerPassInput').fill('test');await page.locator('#officerLoginForm button').click();
  await expect(page.locator('#backendStatusPill')).toContainText('Online',{timeout:90000});
  await page.locator('#fileInput').setInputFiles(path.resolve('work/barcode-fixture.png'));
  await page.locator('#paddleOcrBtn').click();
  const pending=page.waitForResponse(r=>r.url()===api+'/api/scan'&&r.request().method()==='POST');await page.locator('#scanButton').click();
  const scanResponse=await pending;expect(scanResponse.status()).toBe(200);const scan=await scanResponse.json();
  const card=page.locator('#barcodeIdentity');
  await expect(card.locator('#identityGtin')).toHaveValue('9506000140445',{timeout:30000});
  await expect(card.getByRole('link',{name:'Open Verified by GS1'})).toHaveAttribute('href','https://www.gs1.org/services/verified-by-gs1');
  await card.locator('.barcode-entry summary').click();
  await card.locator('#registryGtin').fill('8902579002114');await card.locator('#registryCompany').fill('Example Foods Private Limited');
  await card.getByRole('checkbox').check();await card.getByRole('button',{name:'Compare with label',exact:true}).click();
  await expect(card.getByRole('status')).toContainText('different GTIN');
  await card.locator('#registryGtin').fill('9506000140445');await card.locator('#registryProduct').fill('Classic Oat Biscuits');
  await card.getByRole('checkbox').check();await card.getByRole('button',{name:'Compare with label',exact:true}).click();
  await expect(card.getByRole('status')).toContainText('Comparison saved');
  await expect(card.locator('.barcode-review')).toContainText('Available wording found');
  await expect(card.locator('.barcode-review')).toContainText('Not supplied by lookup');
  const comparison=await request.get(`${api}/api/inspections/${scan.inspection_id}/barcode-identity`);expect(comparison.status()).toBe(200);
  const value=await comparison.json();expect(value.reviews[0].api_verified).toBe(false);expect(value.reviews[0].comparison.company.evidence[0].photo_number).toBe(1);
  const downloadEvent=page.waitForEvent('download');await card.getByRole('button',{name:'Download identity comparison'}).click();const download=await downloadEvent;expect(download.suggestedFilename()).toBe(`NyayaLens-barcode-${scan.inspection_id}.json`);
  await download.saveAs(`work/barcode-identity-${scan.inspection_id}.json`);
  const savedInspection=await (await request.get(`${api}/api/inspections/${scan.inspection_id}`)).json();expect(savedInspection.rules).toEqual(scan.rules);
  await page.setViewportSize({width:390,height:844});await card.scrollIntoViewIfNeeded();
  expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBe(390);
  await page.screenshot({path:'work/barcode-identity-phone.png',fullPage:true});
  await page.reload();await page.locator('#tabOfficerBtn').click();await page.locator('#officerIdInput').fill('barcode-fixture-reviewer');await page.locator('#officerPassInput').fill('test');await page.locator('#officerLoginForm button').click();
  await page.locator('#historyTableBody tr').filter({hasText:`DoCA-LM-2026-${String(scan.inspection_id).padStart(4,'0')}`}).getByRole('button',{name:'Barcode identity'}).click();
  await expect(card.locator('.barcode-review')).toContainText('Available wording found');
  await card.locator('.barcode-entry summary').click();await card.locator('#registryGtin').fill('9506000140445');await card.locator('#registryOutcome').selectOption('not_found');await card.getByRole('checkbox').check();await card.getByRole('button',{name:'Compare with label',exact:true}).click();
  await expect(card.locator('.barcode-review')).toContainText('not proof');
  await expect(card.locator('.barcode-review')).toContainText('Needs review');
  expect(errors).toEqual([]);expect(gs1Requests).toEqual([]);
});
