import { test, expect } from '@playwright/test';
import path from 'node:path';

test('Expo app preserves scanning, results, advisor, settings and officer history', async ({ page, request }) => {
  test.setTimeout(180000);
  await page.setViewportSize({width:390,height:844});
  const errors: string[]=[];
  page.on('pageerror', error => errors.push(error.message));
  await page.addInitScript(()=>localStorage.setItem('doca_tour_done','true'));
  await page.goto(process.env.TEST_MOBILE_URL || 'http://127.0.0.1:8082');
  await page.getByRole('textbox',{name:'Mobile, email or officer ID'}).fill('native-design@example.com');
  await page.getByRole('button',{name:'Enter Citizen Mode',exact:true}).click();
  await expect(page.getByRole('tab',{name:'Scan',exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Scan settings',exact:true}).click();
  await expect(page.getByLabel('State',{exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Scan settings',exact:true}).click();
  await page.getByRole('button',{name:'PaddleOCR',exact:true}).click();
  await expect(page.getByRole('button',{name:'PaddleOCR',exact:true})).toHaveAttribute('aria-selected','true');
  await page.getByRole('button',{name:'Tesseract',exact:true}).click();
  await expect(page.getByRole('button',{name:'Tesseract',exact:true})).toHaveAttribute('aria-selected','true');
  await page.getByRole('button',{name:'Both',exact:true}).click();
  const chooser=page.waitForEvent('filechooser');
  await page.getByRole('button',{name:'Add photos',exact:true}).click();
  await (await chooser).setFiles(path.resolve('work/migration-coffee.jpg'));
  await expect(page.getByRole('button',{name:'Remove photo 1',exact:true})).toBeVisible();
  await page.screenshot({path:'work/expo-scanner.png'});
  const response=page.waitForResponse(r=>r.url().endsWith('/api/scan')&&r.request().method()==='POST');
  await page.getByRole('button',{name:'Run Legal Metrology Verification',exact:true}).click();
  const http=await response;
  expect(http.status()).toBe(200);
  const scan=await http.json();
  expect(scan.ocr_engine).toBe('hybrid');
  expect(scan.rules.mrp.detected_value).toBe('₹ 99.00');
  await expect(page.getByRole('tab',{name:'Results',exact:true})).toHaveAttribute('aria-selected','true');
  await expect(page.getByText('Extracted: ₹ 99.00',{exact:true})).toBeVisible();
  await expect(page.getByRole('button',{name:'Download PDF',exact:true})).toBeVisible();
  const pdf=await request.get((process.env.TEST_API_URL||'http://127.0.0.1:8000')+scan.report_pdf_url);
  expect((await pdf.body()).subarray(0,4).toString()).toBe('%PDF');
  await page.getByRole('button',{name:'Prepare Complaint Draft',exact:true}).click();
  await expect(page.getByRole('textbox',{name:'Recipient email'})).toBeVisible();
  await page.getByRole('button',{name:'Close',exact:true}).click();
  await page.getByRole('tab',{name:'Advisor',exact:true}).click();
  await page.getByRole('textbox',{name:'Ask the packaging advisor'}).fill('cooling charges above MRP');
  await page.getByRole('button',{name:'Send',exact:true}).click();
  await expect(page.getByText('Packaging FAQ',{exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Settings',exact:true}).click();
  await page.getByRole('button',{name:'Switch to dark appearance',exact:true}).click();
  await page.getByRole('button',{name:'Close',exact:true}).click();
  await page.screenshot({path:'work/expo-advisor-dark.png'});
  await page.getByRole('button',{name:'Settings',exact:true}).click();
  await page.getByRole('button',{name:'Switch account',exact:true}).click();
  await page.getByRole('button',{name:'Officer demo',exact:true}).click();
  await page.getByRole('textbox',{name:'Mobile, email or officer ID'}).fill('NATIVE-DESIGN-QA');
  await page.getByRole('textbox',{name:'Demo officer password'}).fill('demo');
  await page.getByRole('button',{name:'Enter Officer Mode',exact:true}).click();
  await page.getByRole('tab',{name:'History',exact:true}).click();
  await expect(page.getByRole('button',{name:'Export CSV',exact:true})).toBeVisible();
  await expect(page.getByRole('button',{name:'Export JSON',exact:true})).toBeVisible();
  expect(errors).toEqual([]);
});
